### ISSUE TITLE
Editing resource in manager : Please wait. Loading map...

### ISSUE THREAD

**Issue by Spheerys** [osucomm/geotv#1]
Hi !

I want to try you add on but I have a problem during resource edition on the manager.
The TV Geofence is set correctly (I think), but on the TV tab of a resource, the map is not loading : "Please wait. Loading map..."

And nothing happened...

Maybe the Google API changed thse 2 past years ?

**Comment by electrickite** [comment]
I installed GeoTV 0.2.0 on a fresh copy of MODX 2.4 and could not reproduce the error you describe. You might try checking your browser's console or network logs to see if those give any clues.

**Comment by Spheerys** [comment]
You're right : I try on another instance and it's working well :)
I will check what's wrong on the other instance.

**Comment by Spheerys** [comment]
Very strange : on my first instance, where I had the issue, after upgrading to GeoTv 1.0.0, the Geographic Area works perfectly, but the new Geographic Point has the error "Please wait. Loading map..."

Worse : on my other MODX instance, where the "Geographic Fence" worked well out of the box, after upgrade I have the same issue than with my first MODx insatnce : the new Geographic Point has the error "Please wait. Loading map..." and the Geographic Area works perfectly.

I'm continuing the investigation.

Maybe I reopen this issue in case...

**Comment by Spheerys** [comment]
OK I can reproduce the error "Please wait. Loading map..." on the two instances if I'm setting on the TV the default lattitude and/or the default longitude like this :
- lattitude : 42.9616 
- longitude : 2.2671

Maybe I don't set them correctly ?
Didn't care if I set Area or Point.
If I unset the default values, the map is loading correctly when I'm editing a resource.

**Comment by electrickite** [comment]
I am unable to reproduce this issue. Tried on MODX 2.2, 2.3, and 2.4. Set the co-ordinates you provided as defaults and the map loaded fine.

Can you provide more details? What version of MODX? What browser version? Anything in the MODX error logs? Any errors in your browser's javascript console?

**Comment by Spheerys** [comment]
In few days I will try on another MODX instance.

For now, on my two instances, I have MODX 2.4.2
I'm using Firefox but the issue occurs with Opera and Midori
I have no MODX error log.
But the interresting thing is on the JS console.
When the problem occurs, I have the third line :
![geobug-1](https://cloud.githubusercontent.com/assets/2228364/12462943/49f3a0c8-bfc1-11e5-9e09-0ce5a577bb8d.png)

And when I'm clinking on it, I have this :
![geobug-2](https://cloud.githubusercontent.com/assets/2228364/12462951/55b4ad3a-bfc1-11e5-9d9c-536d316d170a.png)

It's looks like a comma/dot problem didn't it ?
However, on the TV setting, I use dots on the latitude and longitude !

**Comment by electrickite** [comment]
@Spheerys Thanks! That's very helpful. Looks like some kind of localization issue. I'll take a look.

**Comment by electrickite** [comment]
Problem was caused by locale settings and decimal separator inconsistencies. Version 1.1.0 should resolve this issue.

**Comment by Spheerys** [comment]
Thank you :)
