### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by mishanthrop** [osucomm/geotv#10]
> Uncaught TypeError: Cannot read property 'DrawingManager' of undefined

``` javascript
var drawingManager = new google.maps.drawing.DrawingManager({
  /* some code */
});
```

**Comment by electrickite** [comment]
Please provide more information:
- MODX version
- Browser version
- GeoTV version
- Other installed extras
- Your MODX language settings and locale
- Steps to reproduce this error

**Comment by mishanthrop** [comment]
Hm-m, now it works. Reinstalling helps. May be problem was on google side.
- MODX Revolution 2.4.0-dev (traditional)
- Opera 34
- 1.2.0-pl
- —
- ru
- Install GeoTV, create two TV (area and point), assign it to template, create resource.

**Comment by mishanthrop** [comment]
O-ops. There is yet another plugin for google maps was enabled.

**Comment by electrickite** [comment]
Yes, that could cause conflicts. GeoTV requires the Google Maps drawing library. If another extra loaded Google Maps without it, that would probably cause this error.
