### ISSUE TITLE
Why If or Output filter doesn't works in geopoints_point_tpl ?

### ISSUE THREAD

**Issue by Spheerys** [osucomm/geotv#11]
As you know, I'm using GetResource with GeoTV to build a geojson file with all POIs registered inside resources classified in Categories (their MODX parent).

I want to make If tests inside the geopoints_point_tpl but neither are working (I have nothing, no color, no error...) :

```
        {
          "type": "Feature",
          "geometry": { "type": "Point", "coordinates": [ [[+longitude]], [[+latitude]] ] },
          "properties": {
            "_storage_options": {
               "color": "
                 [[If?&subject=`[[+parent]]`&operator=`EQ`&operand=`38`&then=`DarkRed`]]
                 [[+parent:is=`38`:then=`DarkRed`]]
               ",
               "iconClass": "Drop"
            },
            "type": "cat[[+parent]]",
            "name": "[[+pagetitle]]",
            "description": "[[+tv.Description]]"
          }
        }
```

I tried them cached, uncached... no change...
Notice the [[+parent]] placeholder working well.

Do you have any idea ? 
I can go on MODX board support to ask, in case it's not relevant to GeoTV.

**Comment by electrickite** [comment]
I would guess this has something to do with caching. Maybe you're calling the TV tag cached?

GeoTV runs your template chunk through the `$modx->getChunk()` method, so it should run the entire MODX parser. 

See https://rtfm.modx.com/revolution/2.x/developing-in-modx/other-development-resources/class-reference/modx/modx.getchunk

**Comment by Spheerys** [comment]
Yes it was this :)
