### ISSUE TITLE
Usability improvements for TV data input

### ISSUE THREAD

**Issue by vierkantemeter** [osucomm/geotv#14]
While I was translating geotv, I've came up with some improvements to make it more user friendly.
- **Example of a latitude and longitude value**. Because there are so many ways to write a coordinate:
  - 51,85242°
  - 51°51.145'
  - 51°51'08.7"
  - 51.5108

it would be handy to give an example.

So, this could be very useful:
![voila_capture 2016-01-25_12-32-09_pm](https://cloud.githubusercontent.com/assets/487567/12550023/5b743666-c361-11e5-8d89-fb322a674646.jpg)
- **Example and range of the zoom level**. I even don't know what to enter in this field. A number? And what's the min and max?

**Comment by Spheerys** [comment]
I did it in my french translation ^^
But you're right, it should be set in the default english translation :)

**Comment by vierkantemeter** [comment]
I've also implemented this in my Dutch translation (https://github.com/electrickite/geotv/pull/13). Only zoom level needs to be added when it's clear what the levels are.

**Comment by Spheerys** [comment]
I also waited for the zoom level because we will work on OSM support on GeoTV soon :)

**Comment by electrickite** [comment]
@vierkantemeter So you would like example values for latitude, longitude, and zoom in the default lexicon?

**Comment by vierkantemeter** [comment]
Yes, just like in the image. Although it's a suggestion. So you decide :)
Op 25 jan. 2016 21:32 schreef "Corey Hinshaw" notifications@github.com:

**Comment by electrickite** [comment]
@vierkantemeter @Spheerys @kinaz If you could check the latest lexicon files, they've been updated with example values. Please let me know if the translations are ok. I just plugged them into Google :smile:

**Comment by vierkantemeter** [comment]
Great! The Dutch translation was actually French ;)
I've updated it an created PR https://github.com/electrickite/geotv/pull/15

**Comment by kinaz** [comment]
@electrickite thanks! I've left some comments in the code.

**Comment by electrickite** [comment]
@vierkantemeter Woops! Sorry, thanks for the correction.
