### ISSUE TITLE
GoogleMaps KeyMapError

### ISSUE THREAD

**Issue by achterbahn** [osucomm/geotv#17]
I get a

 `js?v=3.exp&libraries=drawing:31 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error`

when inserting the TV into a template.

**Comment by Spheerys** [comment]
I have the same error.
Maybe GeoTV author disabled his own GoogleMaps API key ?
But I didn't have found yet where it is hard coded.

@achterbahn did you finally used GeoTV with success ?

I already have an instance of GeoTV which still working well on another website. No API Key problem...

**Comment by achterbahn** [comment]
I really don't remember, where I used that Extra, unfortunately. Probably I never used it on a productive site.

**Comment by Spheerys** [comment]
I have found a work around.
First, create your API key here : https://developers.google.com/maps/documentation/javascript/get-api-key
Second, edit the 8th line of the 2 files /core/components/geotv/tv/input/tpl/geotv_geofence.tpl and /core/components/geotv/tv/input/tpl/geotv_geopoint.tpl on this way (just adding the system key as parameter) : 
```
    document.write('<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=drawing&key=*******************************"><\/script>');
```

It's too bad the author of this MODX addon don't have time to maintain GeoTV
It's a very well thinking addon to use geolocation on MODX...

**Comment by electrickite** [comment]
Thanks for posting your fix! Happy to accept a pull request with those changes.

**Comment by Spheerys** [comment]
I'm OK to make a PR but initialy I would use a system setting key as [[++googlemaps_api_key]] but this MODX tag was not interpreted by the manager !
I don't like hard code the api key...

**Comment by electrickite** [comment]
GeoTV 1.3.0-pl resolves this issue by adding a Google Maps API Key system setting.
