### ISSUE TITLE
Locale problem in [[+latitude]] [[+longitude]] : comma instead dot

### ISSUE THREAD

**Issue by Spheerys** [osucomm/geotv#7]
I have found another small locale problem if the system use comma instead of dot on rendered latitude/longitude.
The get around is to use the output filter replace like this : 

```
[[+latitude:replace=`,==.`]]
```

But a replacement directly on GeoTV will be more effective :)

**Comment by electrickite** [comment]
I'm not sure the best way to handle this, since a comma decimal separator is valid in decimal degree notation and your system's locale setting is responsible for formatting numbers.

Would a decimal separator setting in the TV output options work? Perhaps defaulting to a "dot" separator?

**Comment by Spheerys** [comment]
Indeed☺

**Comment by electrickite** [comment]
Added a decimal separator field in 2a02b199a6c5d8a444fc73b7059415588a6cd6a9

It defaults to the separator defined in the MODX system locale.

**Comment by Spheerys** [comment]
:+1:
