### ISSUE TITLE
Possibility to have a last geopoints_point_tpl template different

### ISSUE THREAD

**Issue by Spheerys** [osucomm/geotv#9]
Hi :)

I'm using GeoTV to generate a GeoJSON file, which will be used with a map like GoogleMap or OSM, to geolocate points.

With MODX and GeoTV, I'm generating a file like this :

```
{
  "type": "FeatureCollection",
  "features": [
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [
              42.96047369,
              2.25736856
            ]
          },
          "properties": {
            "_storage_options": {
              "color": "Red"
            },
            "type": "cat36",
            "name": "France Cactus",
            "description": "Vente de cactus, succulentes & plantes grasses",
            "id": "id69"
          }
        },
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [
              42.95982867,
              2.25749731
            ]
          },
          "properties": {
            "_storage_options": {
              "color": "Red"
            },
            "type": "cat36",
            "name": "Le Fournil Bio de Luc",
            "description": "Pains, viennoiseries, patisseries & pause déjeuner",
            "id": "id43"
          }
        },
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [
              42.95838728,
              2.26006955
            ]
          },
          "properties": {
            "_storage_options": {
              "color": "Red"
            },
            "type": "cat36",
            "name": "Nougalet",
            "description": "Fabrication de chocolats artisanaux",
            "id": "id42"
          }
        },
 ]
}
```

But I found a JSON syntax problem : the last point _must not_ have the comma just before the last closing bracket (3 lines before the end).
Under MODX, there is often (with Snippet) a parameter to set the template to use for the last item.
I don't know how to implement this king of functionnality, or how to find a work around for now...

**Comment by electrickite** [comment]
This is the purpose of the "Point Separator" in the TV output options. Say you had a wrapper template chunk:

```
[ [[+points]] ]
```

And a point template chunk:

```
{ lat: [[+latitude]], lng: [[+longitude]] }
```

And set the Point Separator to `,` (a comma). This will insert a comma between each point, so your output might look like this:

```
[ {lat: 123.456, lng: 23.678},{lat: 123.456, lng: 23.678},{lat: 12.456, lng: 73.678} ]
```

Which is valid JSON.

**Comment by Spheerys** [comment]
Ok great :) Except this point separator doesn't works in my instance...
I will check on another instance...

**Comment by Spheerys** [comment]
In fact, at first time I thought this "Point separator" was used when the multiple selections was enabled :)

However, I can't use properly the "point separator" setting : it is innoperant on the output...
![sep](https://cloud.githubusercontent.com/assets/2228364/12530040/72d57b72-c1d0-11e5-8b51-0e8fa90cc800.png)

**Comment by electrickite** [comment]
I'm not sure I understand how you are generating the JSON you posted. It looks like you're building it using a getResources call...

What does your `geopoints_points_tpl` chunk look like?

**Comment by Spheerys** [comment]
Yes, you are right : I'm using GetResource :o/
I was look a little bit heavy at first time, but I didn't find another way (for now!)

My GetResource call : 

```
{
  "type": "FeatureCollection",
  "features": [
    [[!getResources? &parents=`19` &tpl=`FichesProJSONTpl`  &includeTVs=`1` &includeTVList=`Geolocalisation,Description` &processTVs=`1` &processTVList=`Geolocalisation` &limit=`500`]]
 ]
}
```

My FichesProJSONTpl :

```
[[+tv.Geolocalisation]]
```

My geopoints_wrapper_tpl : 

```
[[+points]]
```

And finally my geopoints_point_tpl :

```
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [
              [[+latitude]],
              [[+longitude]]
            ]
          },
          "properties": {
            "_storage_options": {
              "color": "Red"
            },
            "type": "cat[[+parent]]",
            "name": "[[+pagetitle]]",
            "description": "[[+tv.Description]]",
            "id": "id[[+id]]"
          }
        }
```

How would you did it ?

**Comment by electrickite** [comment]
You are correct in thinking the point separator only separates multiple points for the same resource.

Because you only have one point per resource, you'll need to add the separator to the getResources call, probably using

```
&outputSeparator=`,`
```

See the getResources docs for more information: https://rtfm.modx.com/extras/revo/getresources#getResources-Usage

**Comment by Spheerys** [comment]
Yes, but there is another problem in this case :)

The GetResource call generate output item even if there is no coordinate on the retrieved resource.
So the ouput will be : 

```
{
  "type": "FeatureCollection",
  "features": [
,,,,,,,,
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [
              42.96047369,
              2.25736856
            ]
          },
          "properties": {
            "_storage_options": {
              "color": "Red"
            },
            "type": "cat36",
            "name": "France Cactus",
            "description": "Vente de cactus, succulentes & plantes grasses",
            "id": "id69"
          }
        },,,,
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [
              42.95982867,
              2.25749731
            ]
          },
          "properties": {
            "_storage_options": {
              "color": "Red"
            },
            "type": "cat36",
            "name": "Le Fournil Bio de Luc",
            "description": "Pains, viennoiseries, patisseries & pause déjeuner",
            "id": "id43"
          }
        },,
        {
          "type": "Feature",
          "geometry": {
            "type": "Point",
            "coordinates": [
              42.95838728,
              2.26006955
            ]
          },
          "properties": {
            "_storage_options": {
              "color": "Red"
            },
            "type": "cat36",
            "name": "Nougalet",
            "description": "Fabrication de chocolats artisanaux",
            "id": "id42"
          }
        },,,,
 ]
}
```

You can see a comma for each resource retrieved by GetResource, even them without GeoTV filled, and I don't want them :o(

**Comment by electrickite** [comment]
Well, then you'll need to filter those resources out of your getResources call, perhaps using the `tvFilters` property.

Regardless you won't be able to solve this issue using GeoTV even if a last point template were implemented. It would be the last point on a resource with multiple points selected.

A template variable has no way to know that it is attached to the last resource in a collection.

**Comment by Spheerys** [comment]
BINGO !

I made my wonderfull Json file with this GetResources call :

```
{
  "type": "FeatureCollection",
  "features": [
    [[!getResources? 
       &parents=`19` 
       &tpl=`@INLINE [[+tv.Geolocalisation]]` 
       &includeTVs=`1` 
       &includeTVList=`Geolocalisation,Description` 
       &processTVs=`1` 
       &processTVList=`Geolocalisation` 
       &tvFilters=`Geolocalisation!=`
       &limit=`0` 
       &outputSeparator=`,` 
    ]]
 ]
}
```

Thanks a lot for your help :)
